image: node:latest

stages:
  - deploy

deploy:
  stage: deploy
  only:
   - master
  script:
    # Check for ssh-agent + rsync and install if not present
    - "which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y  )"
    - "which rsync || ( apt-get update -y && apt-get install rsync -y )"
    - eval $(ssh-agent -s)
    # Inject the remote's private key
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    # Append keyscan output into known hosts
    - ssh-keyscan $SERVER_IP >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - rsync -r --exclude=".*" $CI_PROJECT_DIR $SERVER_USER@$SERVER_IP:/var/www/api --delete
    - ssh -tt $SERVER_USER@$SERVER_IP
        "cd /var/www/api/mealplaner-backend &&
         npm install &&
         NODE_ENV=production npm run build"




